keys:
  - &ashuramaruzxc_unsigned-int8 age1z5xkrf7tpcs58c53nzjgm7tegv9jk3z73zeyec0q7sjzuvth2dxqz6znnj  # macos
  - &ashuramaruzxc_unsigned-int32 age1srhal9flagunfwyla3zdzdjdm2ramx69ech2p4asu7c9rzw8k9gsjr00sj # home machine
  - &ashuramaruzxc_unsigned-int64 age1tqanhn6e6kuckxq29gvfts3uurv0gdvu5cdmf6raa34ra5mkq99sgp83f8 # server
  # - &bigshaq9999 age1kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - &donteatoreo age1kc4gmk6jztv6schw3mhwwea7nn8emce4uwqufawfwapv9tlgdazqz7fc2w
  # - &lay-by age1kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *ashuramaruzxc_unsigned-int8
          - *ashuramaruzxc_unsigned-int32
          - *ashuramaruzxc_unsigned-int64
          # - *bigshaq9999
          - *donteatoreo
          # - *lay-by
