# This file is auto-generated by an update script
# DO NOT edit manually
{
  buildFirefoxXpiAddon,
  fetchurl,
  lib,
  stdenv,
}:
{
  "ai-warning-for-steam" = buildFirefoxXpiAddon {
    pname = "ai-warning-for-steam";
    version = "1.1.0";
    addonId = "{29428906-aec3-11f0-beb4-6f7e24e82795}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4859426/ai_warning_for_steam-1.1.0.xpi";
    sha256 = "sha256-OYFD0NGp7DS1Gq95X9xc+zKc1g0cjp07zP478oSKjjk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
      ];
    };
  };
  "angular-devtools" = buildFirefoxXpiAddon {
    pname = "angular-devtools";
    version = "1.17.0";
    addonId = "{20a9bb38-ed7c-4faf-9aaf-7c5d241fd747}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4902165/angular_devtools-1.17.0.xpi";
    sha256 = "sha256-oaqxXtG/jsbxiKrk3y8Bi/EYso4TSX7Ig6pIMmFPKEM=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "activeTab"
        "storage"
        "http://*/*"
        "https://*/*"
        "file:///*"
      ];
    };
  };
  "bitwarden-password-manager" = buildFirefoxXpiAddon {
    pname = "bitwarden-password-manager";
    version = "2026.7.0";
    addonId = "{446900e4-71c2-419f-a6a7-df9c091e268b}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4915668/bitwarden_password_manager-2026.7.0.xpi";
    sha256 = "sha256-EYNuudKryZFLsze1fiDFoJz0TyT6Vy9+iGOE/TUKURI=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "*://*/*"
        "alarms"
        "clipboardRead"
        "clipboardWrite"
        "contextMenus"
        "idle"
        "storage"
        "tabs"
        "unlimitedStorage"
        "webNavigation"
        "webRequest"
        "webRequestBlocking"
        "notifications"
      ];
    };
  };
  "darkreader" = buildFirefoxXpiAddon {
    pname = "darkreader";
    version = "4.9.129";
    addonId = "addon@darkreader.org";
    url = "https://addons.mozilla.org/firefox/downloads/file/4899461/darkreader-4.9.129.xpi";
    sha256 = "sha256-9PBH/gjkILbSlhdzjqAKe3hIkrImK35vON0JuO6VikQ=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "tabs"
        "theme"
        "<all_urls>"
      ];
    };
  };
  "facebook-container" = buildFirefoxXpiAddon {
    pname = "facebook-container";
    version = "2.3.12";
    addonId = "@contain-facebook";
    url = "https://addons.mozilla.org/firefox/downloads/file/4451874/facebook_container-2.3.12.xpi";
    sha256 = "sha256-M2m9hlh3hg5tfTg5nVkCswDT1XN6yy0TQv9b6x03gME=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "browsingData"
        "contextualIdentities"
        "cookies"
        "management"
        "storage"
        "tabs"
        "webRequestBlocking"
        "webRequest"
      ];
    };
  };
  "firefox-color" = buildFirefoxXpiAddon {
    pname = "firefox-color";
    version = "2.1.7";
    addonId = "FirefoxColor@mozilla.com";
    url = "https://addons.mozilla.org/firefox/downloads/file/3643624/firefox_color-2.1.7.xpi";
    sha256 = "sha256-t/sHtniPcjPdYiPngOGJtMe5VsJcQEk8KNcCBJMkkpI=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "theme"
        "storage"
        "tabs"
      ];
    };
  };
  "floccus" = buildFirefoxXpiAddon {
    pname = "floccus";
    version = "5.10.2";
    addonId = "floccus@handmadeideas.org";
    url = "https://addons.mozilla.org/firefox/downloads/file/4905907/floccus-5.10.2.xpi";
    sha256 = "sha256-6EvFbE4b/DzDrsKnQAPJlVq49Vo/UTlHVNLHc6/k9IM=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "*://*/*"
        "alarms"
        "bookmarks"
        "storage"
        "unlimitedStorage"
        "tabs"
        "tabGroups"
        "identity"
      ];
    };
  };
  "foxyproxy-standard" = buildFirefoxXpiAddon {
    pname = "foxyproxy-standard";
    version = "9.2";
    addonId = "foxyproxy@eric.h.jung";
    url = "https://addons.mozilla.org/firefox/downloads/file/4472757/foxyproxy_standard-9.2.xpi";
    sha256 = "sha256-jbHGR5mmD3Eh1Rpun2sEGHFZg0SSfJWv6DDCeIDwiF0=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "contextMenus"
        "downloads"
        "notifications"
        "proxy"
        "storage"
        "tabs"
        "webRequest"
        "webRequestAuthProvider"
        "<all_urls>"
      ];
    };
  };
  "kagi-translate" = buildFirefoxXpiAddon {
    pname = "kagi-translate";
    version = "0.1.8";
    addonId = "{bd6be57d-91d7-41d2-b61d-3ba20f7942e5}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4720796/kagi_translate-0.1.8.xpi";
    sha256 = "sha256-9dgTQpg4NoetdbfGdRnd9MPopt53moxbt4jF3tZZBoQ=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "contextMenus"
        "cookies"
        "scripting"
        "notifications"
        "webNavigation"
        "https://*/*"
        "http://*/*"
      ];
    };
  };
  "magnolia@12.34" = buildFirefoxXpiAddon {
    pname = "magnolia@12.34";
    version = "4.4.0.5";
    addonId = "magnolia@12.34";
    url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi&inline=false&commit=4f3c9a6d9cb78bf307ed10f6c647ea43ad6a67d6";
    sha256 = "sha256-aWv6kusp4uC0gjRbfzWJbQx4DRm70gXGGHJvZ0DsDzA=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "cookies"
        "storage"
        "activeTab"
        "webRequest"
        "webRequestBlocking"
        "*://*.24heures.ch/*"
        "*://*.360dx.com/*"
        "*://*.60millions-mag.com/*"
        "*://*.aachener-zeitung.de/*"
        "*://*.abc.es/*"
        "*://*.abcmais.com/*"
        "*://*.abendblatt.de/*"
        "*://*.abqjournal.com/*"
        "*://*.abril.com.br/*"
        "*://*.actu.fr/*"
        "*://*.ad.nl/*"
        "*://*.adage.com/*"
        "*://*.adelaidenow.com.au/*"
        "*://*.adweek.com/*"
        "*://*.aerokurier.de/*"
        "*://*.aerztezeitung.de/*"
        "*://*.afr.com/*"
        "*://*.aisnenouvelle.fr/*"
        "*://*.ajc.com/*"
        "*://*.al-monitor.com/*"
        "*://*.al.com/*"
        "*://*.allgemeine-zeitung.de/*"
        "*://*.alternatives-economiques.fr/*"
        "*://*.ambito.com/*"
        "*://*.americanaffairsjournal.org/*"
        "*://*.americanbanker.com/*"
        "*://*.americanpurpose.com/*"
        "*://*.americastestkitchen.com/*"
        "*://*.aoc.media/*"
        "*://*.apollo-magazine.com/*"
        "*://*.ara.cat/*"
        "*://*.arabalears.cat/*"
        "*://*.architecturaldigest.com/*"
        "*://*.arcinfo.ch/*"
        "*://*.artforum.com/*"
        "*://*.artnet.com/*"
        "*://*.atavist.com/*"
        "*://*.atlantico.fr/*"
        "*://*.auto-motor-und-sport.de/*"
        "*://*.auto-swiat.pl/*"
        "*://*.autocar.co.uk/*"
        "*://*.autohebdo.fr/*"
        "*://*.automobilwoche.de/*"
        "*://*.autonews.com/*"
        "*://*.autoplus.fr/*"
        "*://*.autosport.com/*"
        "*://*.axios.com/*"
        "*://*.azcentral.com/*"
        "*://*.backpacker.com/*"
        "*://*.balkaninsight.com/*"
        "*://*.baltimoresun.com/*"
        "*://*.barandbench.com/*"
        "*://*.barrons.com/*"
        "*://*.bazonline.ch/*"
        "*://*.bbc.com/*"
        "*://*.bd.nl/*"
        "*://*.beleggersbelangen.nl/*"
        "*://*.bendigoadvertiser.com.au/*"
        "*://*.benzinga.com/*"
        "*://*.beobachter.ch/*"
        "*://*.berliner-zeitung.de/*"
        "*://*.berlingske.dk/*"
        "*://*.bernerzeitung.ch/*"
        "*://*.betamtb.com/*"
        "*://*.betternutrition.com/*"
        "*://*.betterprogramming.pub/*"
        "*://*.bhaskar.com/*"
        "*://*.bicycling.com/*"
        "*://*.bienpublic.com/*"
        "*://*.bild.de/*"
        "*://*.billboard.com/*"
        "*://*.bizjournals.com/*"
        "*://*.blick.ch/*"
        "*://*.bloomberg.com/*"
        "*://*.bloombergadria.com/*"
        "*://*.bnd.com/*"
        "*://*.bndestem.nl/*"
        "*://*.bnn.de/*"
        "*://*.boersen-zeitung.de/*"
        "*://*.bonappetit.com/*"
        "*://*.bordermail.com.au/*"
        "*://*.bostonglobe.com/*"
        "*://*.bostonherald.com/*"
        "*://*.braunschweiger-zeitung.de/*"
        "*://*.brisbanetimes.com.au/*"
        "*://*.britannica.com/*"
        "*://*.bt.no/*"
        "*://*.buffalonews.com/*"
        "*://*.business-standard.com/*"
        "*://*.businessam.be/*"
        "*://*.businessdailyafrica.com/*"
        "*://*.businessday.co.za/*"
        "*://*.businessdesk.co.nz/*"
        "*://*.businessinsider.com.pl/*"
        "*://*.businessinsider.com/*"
        "*://*.businessinsider.jp/*"
        "*://*.businessinsider.nl/*"
        "*://*.businessoffashion.com/*"
        "*://*.businesspost.ie/*"
        "*://*.businesstimes.com.sg/*"
        "*://*.cairnspost.com.au/*"
        "*://*.calgaryherald.com/*"
        "*://*.canarias7.es/*"
        "*://*.canberratimes.com.au/*"
        "*://*.capital.bg/*"
        "*://*.capital.fr/*"
        "*://*.capitalgazette.com/*"
        "*://*.caravanmagazine.in/*"
        "*://*.cartacapital.com.br/*"
        "*://*.causeur.fr/*"
        "*://*.cen.acs.org/*"
        "*://*.centralwesterndaily.com.au/*"
        "*://*.centrepresseaveyron.fr/*"
        "*://*.challenges.fr/*"
        "*://*.charentelibre.fr/*"
        "*://*.charliehebdo.fr/*"
        "*://*.charlotteobserver.com/*"
        "*://*.chicago.suntimes.com/*"
        "*://*.chicagobusiness.com/*"
        "*://*.chicagotribune.com/*"
        "*://*.chronicle.com/*"
        "*://*.chunichi.co.jp/*"
        "*://*.cicero.de/*"
        "*://*.cincinnati.com/*"
        "*://*.citeline.com/*"
        "*://*.citywire.com/*"
        "*://*.clarin.com/*"
        "*://*.cleaneatingmag.com/*"
        "*://*.cleveland.com/*"
        "*://*.clicrbs.com.br/*"
        "*://*.climbing.com/*"
        "*://*.cnbc.com/*"
        "*://*.cnn.com/*"
        "*://*.cntraveler.com/*"
        "*://*.codesports.com.au/*"
        "*://*.columbian.com/*"
        "*://*.commentary.org/*"
        "*://*.commercialappeal.com/*"
        "*://*.computerweekly.com/*"
        "*://*.connaissancedesarts.com/*"
        "*://*.correiodopovo.com.br/*"
        "*://*.corriere.it/*"
        "*://*.corriereadriatico.it/*"
        "*://*.corrieredellosport.it/*"
        "*://*.cosmopolitan.com/*"
        "*://*.cosmopolitan.fr/*"
        "*://*.countryliving.com/*"
        "*://*.courant.com/*"
        "*://*.courier-journal.com/*"
        "*://*.couriermail.com.au/*"
        "*://*.courrier-picard.fr/*"
        "*://*.courrierinternational.com/*"
        "*://*.crainscleveland.com/*"
        "*://*.crainsdetroit.com/*"
        "*://*.crainsgrandrapids.com/*"
        "*://*.crainsnewyork.com/*"
        "*://*.crikey.com.au/*"
        "*://*.cronista.com/*"
        "*://*.crusoe.com.br/*"
        "*://*.csmonitor.com/*"
        "*://*.ctinsider.com/*"
        "*://*.ctpost.com/*"
        "*://*.curbed.com/*"
        "*://*.cw.com.tw/*"
        "*://*.cyclingnews.com/*"
        "*://*.dagensmedicin.se/*"
        "*://*.dagsavisen.no/*"
        "*://*.dailyadvertiser.com.au/*"
        "*://*.dailyherald.com/*"
        "*://*.dailyliberal.com.au/*"
        "*://*.dailymail.com/*"
        "*://*.dailypress.com/*"
        "*://*.dailyrecord.co.uk/*"
        "*://*.dailytelegraph.com.au/*"
        "*://*.dailywire.com/*"
        "*://*.dallasnews.com/*"
        "*://*.daytondailynews.com/*"
        "*://*.decanter.com/*"
        "*://*.defector.com/*"
        "*://*.delish.com/*"
        "*://*.democratandchronicle.com/*"
        "*://*.demorgen.be/*"
        "*://*.denik.cz/*"
        "*://*.denverpost.com/*"
        "*://*.derbund.ch/*"
        "*://*.desmoinesregister.com/*"
        "*://*.derstandard.at/*"
        "*://*.destentor.nl/*"
        "*://*.detroitnews.com/*"
        "*://*.df.cl/*"
        "*://*.dhnet.be/*"
        "*://*.diariocorreo.pe/*"
        "*://*.diariodemallorca.es/*"
        "*://*.diariodenavarra.es/*"
        "*://*.diariosur.es/*"
        "*://*.diariovasco.com/*"
        "*://*.diepresse.com/*"
        "*://*.digiday.com/*"
        "*://*.diplomatique.org.br/*"
        "*://*.discovermagazine.com/*"
        "*://*.dispatch.com/*"
        "*://*.dn.no/*"
        "*://*.dn.pt/*"
        "*://*.dn.se/*"
        "*://*.dna.fr/*"
        "*://*.dnevnik.bg/*"
        "*://*.doorbraak.be/*"
        "*://*.dwell.com/*"
        "*://*.eastbaytimes.com/*"
        "*://*.eastwest.eu/*"
        "*://*.echo-online.de/*"
        "*://*.economictimes.com/*"
        "*://*.economist.com/*"
        "*://*.ed.nl/*"
        "*://*.editorialedomani.it/*"
        "*://*.elcomercio.es/*"
        "*://*.elcomercio.pe/*"
        "*://*.elconfidencial.com/*"
        "*://*.elcorreo.com/*"
        "*://*.eldeber.com.bo/*"
        "*://*.eldia.es/*"
        "*://*.eldiario.es/*"
        "*://*.eldiariomontanes.es/*"
        "*://*.elespanol.com/*"
        "*://*.elespectador.com/*"
        "*://*.elle.com/*"
        "*://*.elle.fr/*"
        "*://*.elledecor.com/*"
        "*://*.elmercurio.com/*"
        "*://*.elmundo.es/*"
        "*://*.elnortedecastilla.es/*"
        "*://*.elnuevoherald.com/*"
        "*://*.elobservador.com.uy/*"
        "*://*.elpais.com.uy/*"
        "*://*.elpais.com/*"
        "*://*.elperiodico.com/*"
        "*://*.eltiempo.com/*"
        "*://*.eltribuno.com/*"
        "*://*.eluniversal.com.mx/*"
        "*://*.eluniverso.com/*"
        "*://*.em.com.br/*"
        "*://*.enotes.com/*"
        "*://*.entrepreneur.com/*"
        "*://*.epe.es/*"
        "*://*.epicurious.com/*"
        "*://*.epoch.org.il/*"
        "*://*.espn.com/*"
        "*://*.esprit.presse.fr/*"
        "*://*.esquire.com/*"
        "*://*.estadao.com.br/*"
        "*://*.estrepublicain.fr/*"
        "*://*.euobserver.com/*"
        "*://*.european-rubber-journal.com/*"
        "*://*.europower.no/*"
        "*://*.exame.com/*"
        "*://*.examiner.com.au/*"
        "*://*.expansion.com/*"
        "*://*.express.co.uk/*"
        "*://*.expressnews.com/*"
        "*://*.expresso.pt/*"
        "*://*.farodevigo.es/*"
        "*://*.fastcompany.com/*"
        "*://*.faz.net/*"
        "*://*.femmesdaujourdhui.be/*"
        "*://*.fieldandstream.com/*"
        "*://*.financialexpress.com/*"
        "*://*.financialpost.com/*"
        "*://*.firstthings.com/*"
        "*://*.fiskeribladet.no/*"
        "*://*.flair.be/*"
        "*://*.flair.nl/*"
        "*://*.flugrevue.de/*"
        "*://*.fmrmagazine.com/*"
        "*://*.fnlondon.com/*"
        "*://*.focusplus.de/*"
        "*://*.fokus.se/*"
        "*://*.forbes.com.au/*"
        "*://*.forbes.com/*"
        "*://*.forbes.pl/*"
        "*://*.forbes.ua/*"
        "*://*.foreignaffairs.com/*"
        "*://*.foreignpolicy.com/*"
        "*://*.fortune.com/*"
        "*://*.foxnews.com/*"
        "*://*.fr.de/*"
        "*://*.franc-tireur.fr/*"
        "*://*.freep.com/*"
        "*://*.freiepresse.de/*"
        "*://*.freitag.de/*"
        "*://*.fresnobee.com/*"
        "*://*.ft.com/*"
        "*://*.ftm.eu/*"
        "*://*.ftm.nl/*"
        "*://*.ga.de/*"
        "*://*.gazetadopovo.com.br/*"
        "*://*.gazzetta.it/*"
        "*://*.gbnews.com/*"
        "*://*.geelongadvertiser.com.au/*"
        "*://*.gelderlander.nl/*"
        "*://*.genomeweb.com/*"
        "*://*.gestion.pe/*"
        "*://*.glassdoor.com/*"
        "*://*.globes.co.il/*"
        "*://*.globo.com/*"
        "*://*.glossy.co/*"
        "*://*.goldcoastbulletin.com.au/*"
        "*://*.goodhousekeeping.com/*"
        "*://*.gq.com/*"
        "*://*.granta.com/*"
        "*://*.groene.nl/*"
        "*://*.grubstreet.com/*"
        "*://*.gva.be/*"
        "*://*.haaretz.co.il/*"
        "*://*.haaretz.com/*"
        "*://*.handelsblatt.com/*"
        "*://*.handelszeitung.ch/*"
        "*://*.harpers.org/*"
        "*://*.harpersbazaar.com/*"
        "*://*.harzkurier.de/*"
        "*://*.haz.de/*"
        "*://*.hbr.org/*"
        "*://*.hbvl.be/*"
        "*://*.hd.se/*"
        "*://*.heise.de/*"
        "*://*.heraldsun.com.au/*"
        "*://*.hilltimes.com/*"
        "*://*.hindustantimes.com/*"
        "*://*.historia.fr/*"
        "*://*.historyextra.com/*"
        "*://*.historytoday.com/*"
        "*://*.hln.be/*"
        "*://*.hola.com/*"
        "*://*.housebeautiful.com/*"
        "*://*.houstonchronicle.com/*"
        "*://*.hoy.es/*"
        "*://*.humo.be/*"
        "*://*.hydrogeninsight.com/*"
        "*://*.iai.tv/*"
        "*://*.ideal.es/*"
        "*://*.ikz-online.de/*"
        "*://*.ilfattoquotidiano.it/*"
        "*://*.ilfoglio.it/*"
        "*://*.ilgazzettino.it/*"
        "*://*.ilgiorno.it/*"
        "*://*.illawarramercury.com.au/*"
        "*://*.ilmanifesto.it/*"
        "*://*.ilmattino.it/*"
        "*://*.ilmessaggero.it/*"
        "*://*.ilrestodelcarlino.it/*"
        "*://*.ilsole24ore.com/*"
        "*://*.iltelegrafolivorno.it/*"
        "*://*.iltirreno.it/*"
        "*://*.inc.com/*"
        "*://*.inc42.com/*"
        "*://*.independent.co.uk/*"
        "*://*.indianexpress.com/*"
        "*://*.indiatimes.com/*"
        "*://*.indiatoday.in/*"
        "*://*.indystar.com/*"
        "*://*.inews.co.uk/*"
        "*://*.infolibre.es/*"
        "*://*.informacion.es/*"
        "*://*.infzm.com/*"
        "*://*.inkl.com/*"
        "*://*.inquirer.com/*"
        "*://*.insidehighered.com/*"
        "*://*.interestingengineering.com/*"
        "*://*.internazionale.it/*"
        "*://*.intrafish.com/*"
        "*://*.intrafish.no/*"
        "*://*.investors.com/*"
        "*://*.investorschronicle.co.uk/*"
        "*://*.ipolitics.ca/*"
        "*://*.irishexaminer.com/*"
        "*://*.irishnews.com/*"
        "*://*.irishtimes.com/*"
        "*://*.italian.tech/*"
        "*://*.italiaoggi.it/*"
        "*://*.jacksonville.com/*"
        "*://*.jacobin.de/*"
        "*://*.japantimes.co.jp/*"
        "*://*.jazzwise.com/*"
        "*://*.jeuneafrique.com/*"
        "*://*.jgnt.co/*"
        "*://*.journaldemillau.fr/*"
        "*://*.journaldemontreal.com/*"
        "*://*.journaldequebec.com/*"
        "*://*.journaldunet.com/*"
        "*://*.journalnow.com/*"
        "*://*.journalstar.com/*"
        "*://*.jpost.com/*"
        "*://*.jsonline.com/*"
        "*://*.kansas.com/*"
        "*://*.kansascity.com/*"
        "*://*.kathimerini.gr/*"
        "*://*.kentucky.com/*"
        "*://*.kleinezeitung.at/*"
        "*://*.kn-online.de/*"
        "*://*.knack.be/*"
        "*://*.knoxnews.com/*"
        "*://*.kompas.id/*"
        "*://*.komputerswiat.pl/*"
        "*://*.krautreporter.de/*"
        "*://*.ksta.de/*"
        "*://*.kurier.at/*"
        "*://*.kw.be/*"
        "*://*.kystens.no/*"
        "*://*.la-croix.com/*"
        "*://*.labusinessjournal.com/*"
        "*://*.lacote.ch/*"
        "*://*.ladepeche.fr/*"
        "*://*.ladiaria.com.uy/*"
        "*://*.lagaceta.com.ar/*"
        "*://*.lalibre.be/*"
        "*://*.lalsace.fr/*"
        "*://*.lamanchelibre.fr/*"
        "*://*.lamontagne.fr/*"
        "*://*.lanacion.com.ar/*"
        "*://*.lanazione.it/*"
        "*://*.lance.com.br/*"
        "*://*.lanuovasardegna.it/*"
        "*://*.laprovincia.es/*"
        "*://*.lardennais.fr/*"
        "*://*.larepubliquedespyrenees.fr/*"
        "*://*.larioja.com/*"
        "*://*.lasegunda.com/*"
        "*://*.lasprovincias.es/*"
        "*://*.lastampa.it/*"
        "*://*.latercera.com/*"
        "*://*.latimes.com/*"
        "*://*.lavanguardia.com/*"
        "*://*.lavenir.net/*"
        "*://*.laverdad.es/*"
        "*://*.lavoixdunord.fr/*"
        "*://*.lavoz.com.ar/*"
        "*://*.lavozdigital.es/*"
        "*://*.law.com/*"
        "*://*.le1hebdo.fr/*"
        "*://*.lecanardenchaine.fr/*"
        "*://*.lecho.be/*"
        "*://*.lecourrierdesstrateges.fr/*"
        "*://*.ledauphine.com/*"
        "*://*.ledevoir.com/*"
        "*://*.lefigaro.fr/*"
        "*://*.legrandcontinent.eu/*"
        "*://*.lehighvalleylive.com/*"
        "*://*.lejdd.fr/*"
        "*://*.lejsl.com/*"
        "*://*.lemagit.fr/*"
        "*://*.lemessager.fr/*"
        "*://*.lemonde.fr/*"
        "*://*.lenouveleconomiste.fr/*"
        "*://*.lenouvelliste.ch/*"
        "*://*.leparisien.fr/*"
        "*://*.lepoint.fr/*"
        "*://*.leprogres.fr/*"
        "*://*.lequipe.fr/*"
        "*://*.lequotidiendumedecin.fr/*"
        "*://*.lequotidiendupharmacien.fr/*"
        "*://*.lerevenu.com/*"
        "*://*.lescienze.it/*"
        "*://*.lesechos.fr/*"
        "*://*.lesinrocks.com/*"
        "*://*.lesoir.be/*"
        "*://*.lesoleil.com/*"
        "*://*.lest-eclair.fr/*"
        "*://*.letelegramme.fr/*"
        "*://*.letemps.ch/*"
        "*://*.levante-emv.com/*"
        "*://*.levif.be/*"
        "*://*.lexpress.fr/*"
        "*://*.libelle.be/*"
        "*://*.libelle.nl/*"
        "*://*.liberation-champagne.fr/*"
        "*://*.liberation.fr/*"
        "*://*.linda.nl/*"
        "*://*.lindependant.fr/*"
        "*://*.linforme.com/*"
        "*://*.literaryreview.co.uk/*"
        "*://*.livelaw.in/*"
        "*://*.livemint.com/*"
        "*://*.ln-online.de/*"
        "*://*.lne.es/*"
        "*://*.loebclassics.com/*"
        "*://*.loeildelaphotographie.com/*"
        "*://*.lopinion.fr/*"
        "*://*.losandes.com.ar/*"
        "*://*.lrb.co.uk/*"
        "*://*.lunion.fr/*"
        "*://*.lvz.de/*"
        "*://*.macrobusiness.com.au/*"
        "*://*.madison.com/*"
        "*://*.magazyn-kuchnia.pl/*"
        "*://*.mallorcazeitung.es/*"
        "*://*.manoramaonline.com/*"
        "*://*.marca.com/*"
        "*://*.margriet.nl/*"
        "*://*.marketwatch.com/*"
        "*://*.masslive.com/*"
        "*://*.maz-online.de/*"
        "*://*.mcall.com/*"
        "*://*.mcclatchydc.com/*"
        "*://*.medium.com/*"
        "*://*.medscape.com/*"
        "*://*.menshealth.com/*"
        "*://*.mercurynews.com/*"
        "*://*.meretmarine.com/*"
        "*://*.merkur.de/*"
        "*://*.mexiconewsdaily.com/*"
        "*://*.miamiherald.com/*"
        "*://*.mid-day.com/*"
        "*://*.midilibre.fr/*"
        "*://*.milanofinanza.it/*"
        "*://*.milenio.com/*"
        "*://*.mittelbayerische.de/*"
        "*://*.mlive.com/*"
        "*://*.modernhealthcare.com/*"
        "*://*.modernretail.co/*"
        "*://*.monacomatin.mc/*"
        "*://*.monocle.com/*"
        "*://*.morgenpost.de/*"
        "*://*.motorradonline.de/*"
        "*://*.motorsportmagazine.com/*"
        "*://*.moustique.be/*"
        "*://*.mundodeportivo.com/*"
        "*://*.musicomh.com/*"
        "*://*.mv-voice.com/*"
        "*://*.nation.africa/*"
        "*://*.nationalgeographic.com.es/*"
        "*://*.nationalgeographic.com/*"
        "*://*.nationalgeographic.it/*"
        "*://*.nationalgeographic.nl/*"
        "*://*.nationalpost.com/*"
        "*://*.nationalreview.com/*"
        "*://*.nature.com/*"
        "*://*.nautil.us/*"
        "*://*.nbcnews.com/*"
        "*://*.ndtvprofit.com/*"
        "*://*.neuepresse.de/*"
        "*://*.newcastleherald.com.au/*"
        "*://*.newcriterion.com/*"
        "*://*.newrepublic.com/*"
        "*://*.news-press.com/*"
        "*://*.newscientist.com/*"
        "*://*.newsday.com/*"
        "*://*.newslaundry.com/*"
        "*://*.newsobserver.com/*"
        "*://*.newstatesman.com/*"
        "*://*.newsweek.com/*"
        "*://*.newsweek.pl/*"
        "*://*.newyorker.com/*"
        "*://*.nhregister.com/*"
        "*://*.niagarafallsreview.ca/*"
        "*://*.nicematin.com/*"
        "*://*.nieuwsblad.be/*"
        "*://*.nikkei.com/*"
        "*://*.nj.com/*"
        "*://*.nola.com/*"
        "*://*.nordlittoral.fr/*"
        "*://*.northerndailyleader.com.au/*"
        "*://*.northjersey.com/*"
        "*://*.noz.de/*"
        "*://*.nrc.nl/*"
        "*://*.nrpyrenees.fr/*"
        "*://*.nrz.de/*"
        "*://*.nsctotal.com.br/*"
        "*://*.ntnews.com.au/*"
        "*://*.nv.ua/*"
        "*://*.nw.de/*"
        "*://*.nwitimes.com/*"
        "*://*.nwzonline.de/*"
        "*://*.nybooks.com/*"
        "*://*.nydailynews.com/*"
        "*://*.nymag.com/*"
        "*://*.nypost.com/*"
        "*://*.nysun.com/*"
        "*://*.nyteknik.se/*"
        "*://*.nytimes.com/*"
        "*://*.nzherald.co.nz/*"
        "*://*.nzz.ch/*"
        "*://*.observador.pt/*"
        "*://*.observer.co.uk/*"
        "*://*.ocbj.com/*"
        "*://*.ocregister.com/*"
        "*://*.ogj.com/*"
        "*://*.oklahoman.com/*"
        "*://*.oko.press/*"
        "*://*.ole.com.ar/*"
        "*://*.omaha.com/*"
        "*://*.on3.com/*"
        "*://*.onet.pl/*"
        "*://*.oprahdaily.com/*"
        "*://*.oregonlive.com/*"
        "*://*.orlandosentinel.com/*"
        "*://*.ostsee-zeitung.de/*"
        "*://*.otz.de/*"
        "*://*.ouest-france.fr/*"
        "*://*.outdoorlife.com/*"
        "*://*.outlookbusiness.com/*"
        "*://*.outlookindia.com/*"
        "*://*.outsideonline.com/*"
        "*://*.ovb-online.de/*"
        "*://*.oxygenmag.com/*"
        "*://*.palmbeachpost.com/*"
        "*://*.paloaltoonline.com/*"
        "*://*.paris-normandie.fr/*"
        "*://*.parismatch.com/*"
        "*://*.parkiet.com/*"
        "*://*.parool.nl/*"
        "*://*.pastemagazine.com/*"
        "*://*.pb.pl/*"
        "*://*.pennlive.com/*"
        "*://*.petitbleu.fr/*"
        "*://*.philanthropy.com/*"
        "*://*.philomag.com/*"
        "*://*.philomag.de/*"
        "*://*.philonomist.com/*"
        "*://*.philosophynow.org/*"
        "*://*.pilotonline.com/*"
        "*://*.pionline.com/*"
        "*://*.pitchfork.com/*"
        "*://*.plasticsnews.com/*"
        "*://*.pnp.de/*"
        "*://*.politicaexterior.com/*"
        "*://*.politico.com/*"
        "*://*.polityka.pl/*"
        "*://*.popsci.com/*"
        "*://*.popularmechanics.com/*"
        "*://*.post-gazette.com/*"
        "*://*.pourlascience.fr/*"
        "*://*.pourleco.com/*"
        "*://*.precisionmedicineonline.com/*"
        "*://*.pressenterprise.com/*"
        "*://*.prevention.com/*"
        "*://*.profi.de/*"
        "*://*.profil.at/*"
        "*://*.project-syndicate.org/*"
        "*://*.prospectmagazine.co.uk/*"
        "*://*.public.fr/*"
        "*://*.publico.es/*"
        "*://*.puck.news/*"
        "*://*.pzc.nl/*"
        "*://*.quora.com/*"
        "*://*.quotidiano.net/*"
        "*://*.quotidianodipuglia.it/*"
        "*://*.qz.com/*"
        "*://*.rechargenews.com/*"
        "*://*.reforme.net/*"
        "*://*.repubblica.it/*"
        "*://*.republicain-lorrain.fr/*"
        "*://*.reuters.com/*"
        "*://*.reviewjournal.com/*"
        "*://*.revistaoeste.com/*"
        "*://*.revue21.fr/*"
        "*://*.revueconflits.com/*"
        "*://*.rheinpfalz.de/*"
        "*://*.richmond.com/*"
        "*://*.rnd.de/*"
        "*://*.roadandtrack.com/*"
        "*://*.rollingstone.com/*"
        "*://*.rotowire.com/*"
        "*://*.rp-online.de/*"
        "*://*.rp.pl/*"
        "*://*.rubbernews.com/*"
        "*://*.rugbypass.com/*"
        "*://*.rugbyrama.fr/*"
        "*://*.rundschau-online.de/*"
        "*://*.runnersworld.com/*"
        "*://*.saarbruecker-zeitung.de/*"
        "*://*.sabado.pt/*"
        "*://*.sacbee.com/*"
        "*://*.saechsische.de/*"
        "*://*.sandiegouniontribune.com/*"
        "*://*.scholastic.com/*"
        "*://*.schwarzwaelder-bote.de/*"
        "*://*.schweizermonat.ch/*"
        "*://*.science-et-vie.com/*"
        "*://*.science.org/*"
        "*://*.sciencenews.org/*"
        "*://*.sciencesetavenir.fr/*"
        "*://*.scientificamerican.com/*"
        "*://*.scmp.com/*"
        "*://*.scotsman.com/*"
        "*://*.sdbj.com/*"
        "*://*.seattletimes.com/*"
        "*://*.semana.com/*"
        "*://*.sfchronicle.com/*"
        "*://*.sfstandard.com/*"
        "*://*.sfvbj.com/*"
        "*://*.shreveportbossieradvocate.com/*"
        "*://*.shz.de/*"
        "*://*.si.com/*"
        "*://*.silive.com/*"
        "*://*.skimag.com/*"
        "*://*.sky.it/*"
        "*://*.slate.com/*"
        "*://*.slideshare.net/*"
        "*://*.sloanreview.mit.edu/*"
        "*://*.smartcompany.com.au/*"
        "*://*.smh.com.au/*"
        "*://*.sofrep.com/*"
        "*://*.sourcingjournal.com/*"
        "*://*.spacenews.com/*"
        "*://*.spectator.com.au/*"
        "*://*.spectator.com/*"
        "*://*.spektrum.de/*"
        "*://*.spglobal.com/*"
        "*://*.spiegel.de/*"
        "*://*.spokesman.com/*"
        "*://*.sportico.com/*"
        "*://*.springermedizin.de/*"
        "*://*.standaard.be/*"
        "*://*.standard.co.uk/*"
        "*://*.standard.net.au/*"
        "*://*.standardmedia.co.ke/*"
        "*://*.star-telegram.com/*"
        "*://*.staradvertiser.com/*"
        "*://*.startribune.com/*"
        "*://*.statesman.com/*"
        "*://*.statnews.com/*"
        "*://*.stcatharinesstandard.ca/*"
        "*://*.stereogum.com/*"
        "*://*.stern.de/*"
        "*://*.stltoday.com/*"
        "*://*.stocknews.com/*"
        "*://*.straitstimes.com/*"
        "*://*.stratfor.com/*"
        "*://*.study.com/*"
        "*://*.stuttgarter-nachrichten.de/*"
        "*://*.stuttgarter-zeitung.de/*"
        "*://*.stylist.co.uk/*"
        "*://*.sudinfo.be/*"
        "*://*.sudouest.fr/*"
        "*://*.sueddeutsche.de/*"
        "*://*.suedkurier.de/*"
        "*://*.sun-sentinel.com/*"
        "*://*.suomensotilas.fi/*"
        "*://*.superdeporte.es/*"
        "*://*.swarajyamag.com/*"
        "*://*.sydsvenskan.se/*"
        "*://*.syracuse.com/*"
        "*://*.tagesanzeiger.ch/*"
        "*://*.tagesspiegel.de/*"
        "*://*.tampabay.com/*"
        "*://*.tdg.ch/*"
        "*://*.techinasia.com/*"
        "*://*.technologyreview.com/*"
        "*://*.techtarget.com/*"
        "*://*.telegraaf.nl/*"
        "*://*.telegraph.co.uk/*"
        "*://*.telerama.fr/*"
        "*://*.tennessean.com/*"
        "*://*.tes.com/*"
        "*://*.texasmonthly.com/*"
        "*://*.the-american-interest.com/*"
        "*://*.the-independent.com/*"
        "*://*.the-past.com/*"
        "*://*.the-scientist.com/*"
        "*://*.the-star.co.ke/*"
        "*://*.the-tls.com/*"
        "*://*.theadvocate.com.au/*"
        "*://*.theadvocate.com/*"
        "*://*.theage.com.au/*"
        "*://*.theamericanconservative.com/*"
        "*://*.theamericanscholar.org/*"
        "*://*.theartnewspaper.com/*"
        "*://*.theatlantic.com/*"
        "*://*.theaustralian.com.au/*"
        "*://*.thebaffler.com/*"
        "*://*.thebanner.com/*"
        "*://*.theblaze.com/*"
        "*://*.thebookseller.com/*"
        "*://*.thebulletin.org/*"
        "*://*.thechronicle.com.au/*"
        "*://*.thecourier.com.au/*"
        "*://*.thecritic.co.uk/*"
        "*://*.thecut.com/*"
        "*://*.thedailybeast.com/*"
        "*://*.thediplomat.com/*"
        "*://*.thedispatch.com/*"
        "*://*.theepochtimes.com/*"
        "*://*.theglobeandmail.com/*"
        "*://*.thehill.com/*"
        "*://*.thehindu.com/*"
        "*://*.thehindubusinessline.com/*"
        "*://*.theintercept.com/*"
        "*://*.thejuggernaut.com/*"
        "*://*.thelampmagazine.com/*"
        "*://*.thelawyer.com/*"
        "*://*.theleaflet.in/*"
        "*://*.thelogic.co/*"
        "*://*.themandarin.com.au/*"
        "*://*.themarker.com/*"
        "*://*.themarket.ch/*"
        "*://*.themercury.com.au/*"
        "*://*.thenation.com/*"
        "*://*.thenewatlantis.com/*"
        "*://*.thenewslens.com/*"
        "*://*.thenewsminute.com/*"
        "*://*.thenewworld.co.uk/*"
        "*://*.thepeterboroughexaminer.com/*"
        "*://*.thepointmag.com/*"
        "*://*.theprovince.com/*"
        "*://*.thequint.com/*"
        "*://*.therecord.com/*"
        "*://*.thesaturdaypaper.com.au/*"
        "*://*.thescottishsun.co.uk/*"
        "*://*.thespec.com/*"
        "*://*.thestage.co.uk/*"
        "*://*.thestar.com/*"
        "*://*.thestate.com/*"
        "*://*.thesun.co.uk/*"
        "*://*.thesun.ie/*"
        "*://*.thetimes.com/*"
        "*://*.theverge.com/*"
        "*://*.theweek.com/*"
        "*://*.thewest.com.au/*"
        "*://*.thewrap.com/*"
        "*://*.thisismoney.co.uk/*"
        "*://*.thueringer-allgemeine.de/*"
        "*://*.tijd.be/*"
        "*://*.timeshighereducation.com/*"
        "*://*.timeslive.co.za/*"
        "*://*.timesunion.com/*"
        "*://*.tirebusiness.com/*"
        "*://*.tlz.de/*"
        "*://*.tokyo-np.co.jp/*"
        "*://*.tomshardware.com/*"
        "*://*.topagrar.com/*"
        "*://*.torontosun.com/*"
        "*://*.towardsdatascience.com/*"
        "*://*.townandcountrymag.com/*"
        "*://*.townsvillebulletin.com.au/*"
        "*://*.tradewindsnews.com/*"
        "*://*.trailrunnermag.com/*"
        "*://*.tri-cityherald.com/*"
        "*://*.triathlete.com/*"
        "*://*.trouw.nl/*"
        "*://*.tubantia.nl/*"
        "*://*.tucson.com/*"
        "*://*.tulsaworld.com/*"
        "*://*.tuttosport.com/*"
        "*://*.twincities.com/*"
        "*://*.unherd.com/*"
        "*://*.uol.com.br/*"
        "*://*.upstreamonline.com/*"
        "*://*.usatoday.com/*"
        "*://*.usinenouvelle.com/*"
        "*://*.utech-polyurethane.com/*"
        "*://*.valeursactuelles.com/*"
        "*://*.vancouversun.com/*"
        "*://*.vanityfair.com/*"
        "*://*.variety.com/*"
        "*://*.varmatin.com/*"
        "*://*.vegetariantimes.com/*"
        "*://*.vibilagare.se/*"
        "*://*.vice.com/*"
        "*://*.vikatan.com/*"
        "*://*.vn.at/*"
        "*://*.vn.nl/*"
        "*://*.vogue.co.uk/*"
        "*://*.vogue.com/*"
        "*://*.voguebusiness.com/*"
        "*://*.vol.at/*"
        "*://*.volksfreund.de/*"
        "*://*.volkskrant.nl/*"
        "*://*.vosgesmatin.fr/*"
        "*://*.vox.com/*"
        "*://*.vulture.com/*"
        "*://*.warontherocks.com/*"
        "*://*.washingtonexaminer.com/*"
        "*://*.washingtonpost.com/*"
        "*://*.watoday.com.au/*"
        "*://*.waz.de/*"
        "*://*.weekendavisen.dk/*"
        "*://*.weeklytimesnow.com.au/*"
        "*://*.wellandtribune.ca/*"
        "*://*.welt.de/*"
        "*://*.weltkunst.de/*"
        "*://*.weser-kurier.de/*"
        "*://*.westernadvocate.com.au/*"
        "*://*.wiesbadener-kurier.de/*"
        "*://*.winnipegfreepress.com/*"
        "*://*.wired.com/*"
        "*://*.wiwo.de/*"
        "*://*.wochenblatt.com/*"
        "*://*.womenshealth.de/*"
        "*://*.womenshealthmag.com/*"
        "*://*.womensrunning.com/*"
        "*://*.wonderzine.com/*"
        "*://*.worldeconomics.com/*"
        "*://*.wp.de/*"
        "*://*.wr.de/*"
        "*://*.wsj.com/*"
        "*://*.wwd.com/*"
        "*://*.wyborcza.biz/*"
        "*://*.wyborcza.pl/*"
        "*://*.wysokieobcasy.pl/*"
        "*://*.ynet.co.il/*"
        "*://*.yogajournal.com/*"
        "*://*.yorkshirepost.co.uk/*"
        "*://*.zeit.de/*"
        "*://*.amplitude.com/*"
        "*://*.ampproject.org/*"
        "*://*.arc-cdn.net/*"
        "*://*.axate.io/*"
        "*://*.blueconic.net/*"
        "*://*.cxense.com/*"
        "*://*.ensighten.com/*"
        "*://*.evolok.net/*"
        "*://*.fewcents.co/*"
        "*://*.matheranalytics.com/*"
        "*://*.memberstack.com/*"
        "*://*.newsmemory.com/*"
        "*://*.omeda.com/*"
        "*://*.onecount.net/*"
        "*://*.pelcro.com/*"
        "*://*.piano.io/*"
        "*://*.pico.tools/*"
        "*://*.poool.fr/*"
        "*://*.qiota.com/*"
        "*://*.sophi.io/*"
        "*://*.steadyhq.com/*"
        "*://*.tinypass.com/*"
        "*://*.wallkit.net/*"
        "*://*.zephr.com/*"
        "*://*.adobedtm.com/*"
        "*://*.blink.net/*"
        "*://*.bwbx.io/*"
        "*://*.californiatimes.com/*"
        "*://*.cedscdn.it/*"
        "*://*.cedsdigital.it/*"
        "*://*.coxohio.com/*"
        "*://*.danzz.ch/*"
        "*://*.emol.cl/*"
        "*://*.epochbase.com/*"
        "*://*.flip-pay.com/*"
        "*://*.ftspecialist-us.com/*"
        "*://*.gjirafa.tech/*"
        "*://*.glanacion.com/*"
        "*://*.go.com/*"
        "*://*.hadrianpaywall.com/*"
        "*://*.ith9ueyuhu.it/*"
        "*://*.mcclatchy.com/*"
        "*://*.nhst.tech/*"
        "*://*.nyt.com/*"
        "*://*.prisa.com/*"
        "*://*.thebaltimorebanner.com/*"
        "*://*.townnews.com/*"
        "*://*.wgchrrammzv.com/*"
        "*://archive.fo/*"
        "*://archive.is/*"
        "*://archive.li/*"
        "*://archive.md/*"
        "*://archive.ph/*"
        "*://archive.vn/*"
        "*://*.djservices.io/*"
        "*://*.fnetcore-api-prod.azurewebsites.net/*"
        "*://*.funkemedien.de/*"
        "*://*.mediafin.be/*"
        "*://*.styria.com/*"
        "*://codebeautify.org/*"
        "*://gitflic.ru/*"
        "*://*/*"
      ];
    };
  };
  "multi-account-containers" = buildFirefoxXpiAddon {
    pname = "multi-account-containers";
    version = "8.3.8";
    addonId = "@testpilot-containers";
    url = "https://addons.mozilla.org/firefox/downloads/file/4867303/multi_account_containers-8.3.8.xpi";
    sha256 = "sha256-MGopSEU2PxWnR46WILQ/keoXYQiHJ4COIye//xbBREc=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "activeTab"
        "cookies"
        "contextMenus"
        "contextualIdentities"
        "history"
        "idle"
        "management"
        "storage"
        "unlimitedStorage"
        "tabs"
        "webRequestBlocking"
        "webRequest"
      ];
    };
  };
  "old-reddit-redirect" = buildFirefoxXpiAddon {
    pname = "old-reddit-redirect";
    version = "2.2.0";
    addonId = "{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4882083/old_reddit_redirect-2.2.0.xpi";
    sha256 = "sha256-WzRv+PfehDBKQCQyY479vawKYXTWKsXChFzOSZjzMCI=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "declarativeNetRequestWithHostAccess"
        "*://reddit.com/*"
        "*://www.reddit.com/*"
        "*://np.reddit.com/*"
        "*://amp.reddit.com/*"
        "*://i.reddit.com/*"
        "*://i.redd.it/*"
        "*://preview.redd.it/*"
      ];
    };
  };
  "react-devtools" = buildFirefoxXpiAddon {
    pname = "react-devtools";
    version = "6.1.1";
    addonId = "@react-devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4432990/react_devtools-6.1.1.xpi";
    sha256 = "sha256-staeIgQCvWuLx9gzlIkVsdbcq7RTodUIcqPbhg/ZLEY=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "scripting"
        "storage"
        "tabs"
        "clipboardWrite"
        "<all_urls>"
      ];
    };
  };
  "reddit-enhancement-suite" = buildFirefoxXpiAddon {
    pname = "reddit-enhancement-suite";
    version = "5.24.10";
    addonId = "jid1-xUfzOsOFlzSOXg@jetpack";
    url = "https://addons.mozilla.org/firefox/downloads/file/4899821/reddit_enhancement_suite-5.24.10.xpi";
    sha256 = "sha256-RXPP2xAZNGfpnh3Vp5LyOuaXZFQMLgbQRE8SqBzcTwo=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "https://*.reddit.com/*"
        "cookies"
        "identity"
        "tabs"
        "history"
        "storage"
        "scripting"
        "unlimitedStorage"
        "https://publish.twitter.com/oembed"
        "https://backend.deviantart.com/oembed"
        "https://api.gyazo.com/api/oembed"
        "https://api.tumblr.com/v2/blog/*/posts"
        "https://xkcd.com/*/info.0.json"
        "https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/*"
        "https://www.googleapis.com/drive/v3/*"
        "https://*.redd.it/*"
        "https://www.flickr.com/services/oembed"
        "https://embed.bsky.app/oembed"
      ];
    };
  };
  "reduxdevtools" = buildFirefoxXpiAddon {
    pname = "reduxdevtools";
    version = "3.2.10";
    addonId = "extension@redux.devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4467343/reduxdevtools-3.2.10.xpi";
    sha256 = "sha256-7ysQoryLDRqETRRuPur/QH6qpjzQVk246v2HDIeoiVY=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "notifications"
        "contextMenus"
        "tabs"
        "storage"
        "file:///*"
        "http://*/*"
        "https://*/*"
      ];
    };
  };
  "search_by_image" = buildFirefoxXpiAddon {
    pname = "search_by_image";
    version = "8.5.3";
    addonId = "{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4840197/search_by_image-8.5.3.xpi";
    sha256 = "sha256-umBEeLUPXEbhMBHqfj4pBqvHsbcst+h7AsT73vpkrjc=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "unlimitedStorage"
        "tabs"
        "activeTab"
        "notifications"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
        "scripting"
      ];
    };
  };
  "steam-database" = buildFirefoxXpiAddon {
    pname = "steam-database";
    version = "4.35";
    addonId = "firefox-extension@steamdb.info";
    url = "https://addons.mozilla.org/firefox/downloads/file/4891926/steam_database-4.35.xpi";
    sha256 = "sha256-N8HNwur6cB42Xrjg7ypQUblW6h6ZQbOZtas/pCFPwSM=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "https://steamdb.info/*"
        "https://steamcommunity.com/*"
        "https://*.steampowered.com/*"
      ];
    };
  };
  "styl-us" = buildFirefoxXpiAddon {
    pname = "styl-us";
    version = "2.4.8";
    addonId = "{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4907275/styl_us-2.4.8.xpi";
    sha256 = "sha256-RVQmiQo4vT7lEQABEuzlFnX4u8IemIviFww65pAMvt8=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "tabs"
        "unlimitedStorage"
        "webNavigation"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
      ];
    };
  };
  "tabliss" = buildFirefoxXpiAddon {
    pname = "tabliss";
    version = "2.6.0";
    addonId = "extension@tabliss.io";
    url = "https://addons.mozilla.org/firefox/downloads/file/3940751/tabliss-2.6.0.xpi";
    sha256 = "sha256-3nZoEPI0scE//bcEeubL8G7XnD0ItRoH5HZvrf8InA8=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
      ];
    };
  };
  "translate-web-pages" = buildFirefoxXpiAddon {
    pname = "translate-web-pages";
    version = "7.5";
    addonId = "{d3a88b28-681e-43b6-ac3d-22f92ba18818}";
    url = "https://addons.mozilla.org/firefox/downloads/file/3656490/translate_web_pages-7.5.xpi";
    sha256 = "sha256-ENWrAcTpe9zxIoYlRYoF/kVHtZ1upBjeDuZHy3Gn6Nk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "storage"
        "activeTab"
        "contextMenus"
      ];
    };
  };
  "user-agent-string-switcher" = buildFirefoxXpiAddon {
    pname = "user-agent-string-switcher";
    version = "0.6.7";
    addonId = "{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4773733/user_agent_string_switcher-0.6.7.xpi";
    sha256 = "sha256-l5oEyaOA8QtxWYCTWm8+hw3/88gQDL45PWW0bbgqslc=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "contextMenus"
        "scripting"
        "declarativeNetRequestWithHostAccess"
        "webRequest"
        "<all_urls>"
      ];
    };
  };
  "view-page-archive" = buildFirefoxXpiAddon {
    pname = "view-page-archive";
    version = "7.3.3";
    addonId = "{d07ccf11-c0cd-4938-a265-2a4d6ad01189}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4871262/view_page_archive-7.3.3.xpi";
    sha256 = "sha256-gcolvUE5LPSwPUwcTDnr1aTqqEDvik0m+Esd05aZmjQ=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "unlimitedStorage"
        "tabs"
        "activeTab"
        "notifications"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
        "scripting"
      ];
    };
  };
  "vue-js-devtools" = buildFirefoxXpiAddon {
    pname = "vue-js-devtools";
    version = "7.7.7";
    addonId = "{5caff8cc-3d2e-4110-a88a-003cc85b3858}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4508409/vue_js_devtools-7.7.7.xpi";
    sha256 = "sha256-VnLNDTKY+lfy9R5GRAEeQVLm4pH28zhgFJXdgDczEWk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
      ];
    };
  };
  "youtube-no-translation" = buildFirefoxXpiAddon {
    pname = "youtube-no-translation";
    version = "2.24.3";
    addonId = "{9a3104a2-02c2-464c-b069-82344e5ed4ec}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4859010/youtube_no_translation-2.24.3.xpi";
    sha256 = "sha256-I8o4CxNTP7POo8qd6Paetv79VGCMhd8ABdNozR2Q/YU=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "*://*.youtube.com/*"
        "*://*.youtube-nocookie.com/*"
      ];
    };
  };
}
