{ lib, config, ... }:
{
  _class = "homeManager";
  _file = ./default.nix;
  key = toString ./default.nix;
  options.hm.hyprland.enable = lib.options.mkEnableOption "Hyprland";

  config = lib.modules.mkIf config.hm.hyprland.enable {
    wayland.windowManager.hyprland.enable = true;
    wayland.windowManager.hyprland.configType = "hyprlang";
    wayland.windowManager.hyprland.settings = {
      ecosystem.no_update_news = true;

      autogenerated = 0;
      #"$killActiveWindow" = ''
      #  hyprctl activewindow | \
      #  grep -oP --color=never 'pid:\s+\K\d+' | \
      #  while read -r pid; do
      #      if kill "$pid"; then
      #          for i in {1..5}; do
      #              sleep 0.5
      #              kill -0 "$pid" 2>/dev/null || exit
      #              [ "$i" -eq 5 ] && kill -9 "$pid"
      #          done
      #      fi
      #  done
      #'';

      bind = [
        # Audio Control
        " ,XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        " ,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        " ,XF86AudioPlay, exec, playerctl play-pause"
        " ,XF86AudioPause, exec, playerctl play-pause"
        " ,XF86AudioNext, exec, playerctl next"
        " ,XF86AudioPrev, exec, playerctl previous"
      ]
      ++ (builtins.concatLists (
        builtins.genList (
          x:
          let
            ws =
              let
                c = (x + 1) / 10;
              in
              builtins.toString (x + 1 - (c * 10));
          in
          [
            "$mainMod, ${ws}, workspace, ${toString (x + 1)}"
            "$mainMod SHIFT, ${ws}, movetoworkspace, ${toString (x + 1)}"
          ]
        ) 10
      ));

      windowrule = [
        {
          name = "shared-suppress-maximize";
          "match:class" = ".*";
          suppress_event = "maximize";
        }
        {
          name = "shared-exe-immediate";
          "match:class" = "^(*.exe)$";
          immediate = true;
        }
      ];

      cursor.no_hardware_cursors = 1;
    };
  };
}
