# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  config,
  lib,
  ...
}:
lib.flatten [
  {
    id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71qTUGASVO_VTqY2-Bq9AoGnhoevVYOdV-5kFzaE-G7FGotoIZ_rzsmZcWGkJEN4egPYu-VnDfMjLd4mNsNNlUVM4JYvjGqEy2iHhHBgad-l-tDga2NHIgOI3KdhDSoAxlKa5cr6CGqrmyg4Zy_6SuZFiJNt4XPN/EIMADPBCBFNMBKOPOOJFEKHNKHDBIEEH_4_9_112_0.crx";
      name = "eimadpbcbfnmbkopoojfekhnkhdbieeh.crx";
      hash = "sha256-zsiHSs2MApMRzzxZqmc19jsdOqBd0Vm1LOmpjcrdQyw=";
    };
    version = "4.9.112";
  }
  {
    id = "cdglnehniifkbagbbombnjghhcihifij";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71o-hWKJPfiRE6JJdxGC3mff8pboipl1RCdI1iI2taqK4b1W3CckXNtnFDPs1w9sNBEUhyWgXN8dNyjBXgIEmCatKxkXJ252etojp9Ln1kaR4_EH0GgF1PLFDIcrx4sAxlKa5bpHludyjqIuA0wtTB3v4Koot-G7/CDGLNEHNIIFKBAGBBOMBNJGHHCIHIFIJ_1_2_2_5.crx";
      name = "cdglnehniifkbagbbombnjghhcihifij.crx";
      hash = "sha256-weiUUUiZeeIlz/k/d9VDSKNwcQtmAahwSIHt7Frwh7E=";
    };
    version = "1.2.2.5";
  }
  {
    id = "hkligngkgcpcolhcnkgccglchdafcnao";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71riSmcKt-_dlxJcLkEKeJVvo3waCq0A4STuFN6-T2_pm7LQBICoxZut_ZN7sMzgy1FQJK8p7EeH7-ZYly6nKrrag79tJ4yXPoIgD9GU1pjixXqtK3y4xmfvcAueqg4AxlKa5et-qQ58tGsutUdIeTE2Rvy-hLCZ/HKLIGNGKGCPCOLHCNKGCCGLCHDAFCNAO_7_1_0_0.crx";
      name = "hkligngkgcpcolhcnkgccglchdafcnao.crx";
      hash = "sha256-xdhkF0HMRjYLK6YPCfUr8aTMkqR/K7ntbgdHttzLd78=";
    };
    version = "7.1.0";
  }
  {
    id = "fmkadmapgofadopljbjfkapdkoienihi";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71qVQsHfHbKOILsz6K7L8VxXT9_w_V8mFWqo4MOCcRwIk3lGg_uUR8qnRM8Th3HRdBrBHu0FZxxSutFmc6ZKv7VQVtbHjuqV145-OYyA6JcaaqtqZxkMi7ND7PFGLAEAxlKa5dMOHdwKX4kdXulKiUhVXBrvcXxj/FMKADMAPGOFADOPLJBJFKAPDKOIENIHI_7_0_1_0.crx";
      name = "fmkadmapgofadopljbjfkapdkoienihi.crx";
      hash = "sha256-X3DIlm39NyFz8bGKVjubF8JGeS58EirqeETOBk8Hfgc=";
    };
    version = "7.0.1";
  }
  {
    id = "lmhkpmbekcpmknklioeibfkpmmfibljd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71pPLIo9pNyaZH_S3ilrJxipX3KzkRTdFKZZ84QSUmjLvuzb1AWySGt8RWZxFSCRw01cj0fL5e9BNsKGVPPRw2ozmKnhgAOCl60j80UdtQJlsg6dKnUQL9zyjcaLc1sAxlKa5exn_Zb5LCCgg6PpyGzutOO86sFa/LMHKPMBEKCPMKNKLIOEIBFKPMMFIBLJD_3_2_10_0.crx";
      name = "lmhkpmbekcpmknklioeibfkpmmfibljd.crx";
      hash = "sha256-IjNQiQdZSwW8ZDNyUxJTuTBuhs9cpUjltOdwfzR4YKM=";
    };
    version = "3.2.10";
  }
  {
    id = "nhdogjmejiglipccpnnnanhbledajbpd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71q0CoRSj6HxVfzMvkdvQlZTi-DnTR4zX0Ot9cR2r5WR37DWVdW1qo_ozmNkM2mpq84k6tjOlrEYd9jqDvEt2TCO-i_mskQq7G90w6j4iydcE3F_5o2aawt5nR7mUPzyAMZSmuUeAMW2c2lxlL4JSzr4Y4j96tBx_w/NHDOGJMEJIGLIPCCPNNNANHBLEDAJBPD_7_7_7_0.crx";
      name = "nhdogjmejiglipccpnnnanhbledajbpd.crx";
      hash = "sha256-v1ZcI/2eLAdO1HFE0FBDNveH5fEFOI9zxihG3ukvASQ=";
    };
    version = "7.7.7";
  }
  {
    id = "ienfalfjdbdpebioblfackkekamfmbnh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71ovyHkWeyQtPD16cICdHkF94wOdIiMHJjS11cJOwRovtqh3OqZZ6TJ9mKN8vzA5mLs83_THzhcbzKt5a252rhvEp2IausH-KL2xCbJIcnUgQQVcd_aebJP9xwxS_OgAxlKa5fdmWNcYKf_OKkOrEevFtHQ9EPsI/IENFALFJDBDPEBIOBLFACKKEKAMFMBNH_1_4_1_0.crx";
      name = "ienfalfjdbdpebioblfackkekamfmbnh.crx";
      hash = "sha256-a+2zdmyuUF0t8rdnr0C3xnvzmKU3hnfKHQ9pcZC7HxE=";
    };
    version = "1.4.1";
  }
  {
    id = "kmcfjchnmmaeeagadbhoofajiopoceel";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71oM28uzacO6zgp3atKoa_9ByybKKxFOFL7n-BXt_0qu1bFI4Y370biG4vwgV8_8TT8L3YYe8uoHyAc-wVBCS4o4I2kp0lMNZRMaLwLt8z3NM-GROz7dT31Exiz5v14AxlKa5blH05wwRI8a42fwbRdko_V4307L/KMCFJCHNMMAEEAGADBHOOFAJIOPOCEEL_0_33_5_0.crx";
      name = "kmcfjchnmmaeeagadbhoofajiopoceel.crx";
      hash = "sha256-SaBM++yovHNqOUyurpcvsfotSUzHxgjc8GHvrLOOiGk=";
    };
    version = "0.33.5.0";
  }
  {
    id = "bhchdcejhohfmigjafbampogmaanbfkg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71o8x8k1TrUYGIZ7P1DDZliNzDKG9sq8dItS_qpJPWN6J8xAhQYjw9L4hUq9U45z39Mh7Jx-bOvZYSFe9IdVET1FQmbjwxETtOC6aMedSSkeMn-KoYlWPBQ9rfBOluQAxlKa5ZiK3XeWgHB6HnFVfGnH5G8QQlXb/BHCHDCEJHOHFMIGJAFBAMPOGMAANBFKG_0_6_6_0.crx";
      name = "bhchdcejhohfmigjafbampogmaanbfkg.crx";
      hash = "sha256-2n0HNRR2NRWTxO96ytORUedOiFAZmopmUHv/S43PB0k=";
    };
    version = "0.6.6";
  }
  {
    id = "hkgfoiooedgoejojocmhlaklaeopbecg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71q3epxGfOwooHeDcD2q41H5bSRQ33Of_pL_KdZyddoMmA0lxoeJHHHBTo4QM_cJo_52R2-zYyGAFnaAJr_vQgBsZMKH8IAn8bbPpJ24-8mRL1PcyhQcypSnRwDCJADGUprlTNedLzj52lx2WI2HNW5VaCsj5l8/HKGFOIOOEDGOEJOJOCMHLAKLAEOPBECG_1_14_0_0.crx";
      name = "hkgfoiooedgoejojocmhlaklaeopbecg.crx";
      hash = "sha256-NaWNfAH9zyLIVpmK5+cb72PUZ3whU5NwCb+9BA45aGc=";
    };
    version = "1.14";
  }
  {
    id = "hipekcciheckooncpjeljhnekcoolahp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71o2pO9Kh0qnttaXL5gvgjsvFifUyJHTJV-w2kv-Dbq1Q6nAO4-J8_GwFtVSGF-fEX3QejvMH50MECWTNKMPDtmmCexXM5GvgH6khI_uiuR6JMq9AMZSmuVQUhTgA7I8Mw3P2CDyvN8Q92AB3g/HIPEKCCIHECKOONCPJELJHNEKCOOLAHP_2_6_0_0.crx";
      name = "hipekcciheckooncpjeljhnekcoolahp.crx";
      hash = "sha256-3a3HVG6dWVRx+EQ48gohNlu3BOzVZrpoZCxnf3chzRY=";
    };
    version = "2.6.0";
  }
  {
    id = "clngdbkpkpeebahjckkjfobafhncgmne";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71qnNiSy6g4F-dtaKGVOCawuiO058n5e9OgyyMaRdhYH5_p8xzbHQpakj_ZdBB5hdMhTwaGV9L0GMY1L6NTcxheCL1Z938j7wSQz28WHAXEZLdFgHgZ0shtuFgraoQUAxlKa5f0Sfqrh-2_tIe4Q7q4YFxlLBr3i/CLNGDBKPKPEEBAHJCKKJFOBAFHNCGMNE_2_3_16_0.crx";
      name = "clngdbkpkpeebahjckkjfobafhncgmne.crx";
      hash = "sha256-NKOL5zkYrZ1axUJ+LS89VyKoUY/ytYwFSz/oEKOp8R4=";
    };
    version = "2.3.16";
  }
  {
    id = "gcknhkkoolaabfmlnjonogaaifnjlfnp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71qAd9nzf7E4wshYGmes9s8s1l9e94DeplM9BAbPYWES1A00Hx3oAPoHVxGbwrS99HVEK_-afZuY03AI-dvK8or8-Wn3wESHLz_22y6gzZC5j9gu0dk-b7rw-povY8oAxlKa5Z-dzZ-cR0V1m2dUZu6Cl2XeWlHH/GCKNHKKOOLAABFMLNJONOGAAIFNJLFNP_9_2_0_0.crx";
      name = "gcknhkkoolaabfmlnjonogaaifnjlfnp.crx";
      hash = "sha256-B0LnrmxNQ3B1iKk89jaIC6Q0k3IP3YEW6yJnW+n4sG4=";
    };
    version = "9.2";
  }
  {
    id = "nngceckbapebfimnlniiiahkandclblb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71oaoanqmu17iSuE6EkuzE-kbn3Z_V1NtZtMvGyEW2QoNcusxaRPmwVwoTWEmLJNHngOYHoU0igEOywp600I2QsDmRnWht2eCQRvjhLJQ1bx-cSPZw5NkcV2w9QVbnl6AMZSmuX4zzIMkGoWiAh34jlUatS_nGfgBQ/NNGCECKBAPEBFIMNLNIIIAHKANDCLBLB_2025_10_0_0.crx";
      name = "nngceckbapebfimnlniiiahkandclblb.crx";
      hash = "sha256-moDhxQwVRvXrYeozLSXsPYR3sSvUEHCrrJZIRjXYmrU=";
    };
    version = "2025.10.0";
  }
  {
    id = "kbmfpngjjgdllneeigpgjifpgocmfgmb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71rw7-GK6uLiWLmKreaol6kt5mgwbDzwRyVldS50mbwj_WvJb1FWjS6aWZtTiTmpH5HpeM81FblSp8q9WWoXQNfETIbMq4jnYZL1BxegWJW63I9jy5AVj4SKQ4AhPGbgAMZSmuVdVA-IhTk0ieympFS9AcbWgp4ZFA/KBMFPNGJJGDLLNEEIGPGJIFPGOCMFGMB_5_24_8_0.crx";
      name = "kbmfpngjjgdllneeigpgjifpgocmfgmb.crx";
      hash = "sha256-wM2vceDp5M96hD7aPYEY0c9x1f/fK8Bz1UVokRTJyxg=";
    };
    version = "5.24.8";
  }
  {
    id = "dneaehbmnbhcippjikoajpoabadpodje";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71r6eyqbAeXOkAknpGXlxIasLqmGNBKPdj1MAZlbHW10JxBnE6st0EKB6GrUtgjkl8v2K8iggZm4f7XlYJBppopN-gS_SP-z5EhVzbwuahy0Wld7uHikFXH78tH5DTsAxlKa5YUgRu9mMswGB41CEajy6HIto9eQ/DNEAEHBMNBHCIPPJIKOAJPOABADPODJE_2_0_9_0.crx";
      name = "dneaehbmnbhcippjikoajpoabadpodje.crx";
      hash = "sha256-26kMNZktrRomwltsAlQMEwiZ/MNv6Fw8GHoJ6GebsRE=";
    };
    version = "2.0.9";
  }
  {
    id = "cnojnbdhbhnkbcieeekonklommdnndci";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71qVaGiFcX3wgYpSIhFzK9eW6FZ9zrwrMzvIz6Zf3AqWNIiD_HHsWGbVku9b1GN2_wPCxkQCyM7C55dye_j41ete60uJ3ZVuqRwBL10uk_YUGVS3-nzBgVYhjCDnxSQAxlKa5W_ZFkqbOzNt0WTecBCwYYJ9LrQH/CNOJNBDHBHNKBCIEEEKONKLOMMDNNDCI_8_3_0_0.crx";
      name = "cnojnbdhbhnkbcieeekonklommdnndci.crx";
      hash = "sha256-mnuiVRW/fDYFIceqb0HZeA4+MUO7Uuw9JXirfmy92Uo=";
    };
    version = "8.3.0";
  }
  {
    id = "pobhoodpcipjmedfenaigbeloiidbflp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AfXM71rZh7VpppTaQMOKlQQruWCgLpu60QTRL925zuGS4V_5fMH1-tDE6duGhNa3tFVlXfeborKaKcyAeT9sv6Z5AQENguLkzXGHJyj5vGo9RCrFszTkkK-sSCqVOEYARrsAxlKa5UcdAB8EKJ8TjsZYZRqsMVsKEDMM/POBHOODPCIPJMEDFENAIGBELOIIDBFLP_6_4_0_0.crx";
      name = "pobhoodpcipjmedfenaigbeloiidbflp.crx";
      hash = "sha256-NbnmP/qRhjrmUghyKSjDMNKGSq1flbLA0qMb1GVgW9c=";
    };
    version = "6.4.0";
  }
]
