# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo4wtafkRJFFtO_DOmG2ktdozuHfLJn3rngw9lgaf6ew5Nb4txBpLskInw1toh1VvrEOHSaitXxFalEP7I3xs6XfUA8Ggt4ZCHiZGoQSksRaYhdEeNLNs4t-uQL8x9QAxlKa5aaMIpn_MK2IC4KHF_Gohvv52i09/EIMADPBCBFNMBKOPOOJFEKHNKHDBIEEH_4_9_118_0.crx";
      name = "eimadpbcbfnmbkopoojfekhnkhdbieeh.crx";
      hash = "sha256-aCAGePzaywNfNUwqSqhsM+GifJPz+NT71RiT0Z6QMkI=";
    };
    version = "4.9.118";
  }
  {
    id = "cdglnehniifkbagbbombnjghhcihifij";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo5Po4IrchEyTOJw-68t2yi9esvW1563WI2fZ--ZhHW6LKYYizYmEp3gqgcrmqWO1VQf86AHxXMwdIesMFCSsDIc8OIQqyMgnwH2PDf8Qej2JkC6iMxkBVwUe4Ja53IAxlKa5WK59zUSbECyLY913h5u1xKFpNqY/CDGLNEHNIIFKBAGBBOMBNJGHHCIHIFIJ_1_2_2_5.crx";
      name = "cdglnehniifkbagbbombnjghhcihifij.crx";
      hash = "sha256-weiUUUiZeeIlz/k/d9VDSKNwcQtmAahwSIHt7Frwh7E=";
    };
    version = "1.2.2.5";
  }
  {
    id = "hkligngkgcpcolhcnkgccglchdafcnao";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo6GlgeK42WDqLEHwzZZgwn8YdDEy5LxSikYei1wkuJQ5MniJLek9Qy3BAgOcWRwi5T93oG5tok01QtTQcen2hiNhCKPX4TvU__cY-oPi8sqz6cqQofIvtGM9JqqjicAxlKa5d31p4J1yT6scjq2zEzXvV6FqkuI/HKLIGNGKGCPCOLHCNKGCCGLCHDAFCNAO_7_2_0_0.crx";
      name = "hkligngkgcpcolhcnkgccglchdafcnao.crx";
      hash = "sha256-yrOjJL3SD0TkpMSjhj3dRNxzHExf5an3WJ+uGaPYGR0=";
    };
    version = "7.2.0";
  }
  {
    id = "fmkadmapgofadopljbjfkapdkoienihi";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7fPyiQm3qdCWLwSKE80MkENrgDNx6OyMvyZkVXCOLLj2xt0r2aWQF24CnXDbcfH4UarT0mmUZgJvqrfEspkA_AdUH-hVbH4Tq9ZLNFurzKMGkwsdu0B13j1CRAzqEAxlKa5VpbXGMLD1sCFPF42xJfPErdn1cS/FMKADMAPGOFADOPLJBJFKAPDKOIENIHI_7_0_1_0.crx";
      name = "fmkadmapgofadopljbjfkapdkoienihi.crx";
      hash = "sha256-X3DIlm39NyFz8bGKVjubF8JGeS58EirqeETOBk8Hfgc=";
    };
    version = "7.0.1";
  }
  {
    id = "lmhkpmbekcpmknklioeibfkpmmfibljd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo5WLBSGAl0-K6uDGJmwjM7DhvJnO7CmGOz-1_rNeUZ1ujyA_uVZ3tDDEipT5RnBNA8FdJoxm6TC372r_uqevLK_mfBzlAYzF8b5RqVLc6HsLTHX0p3qGFec34eszJoAxlKa5a9fjaiVnkfMGOp2YuXNvXoBFzyE/LMHKPMBEKCPMKNKLIOEIBFKPMMFIBLJD_3_2_10_0.crx";
      name = "lmhkpmbekcpmknklioeibfkpmmfibljd.crx";
      hash = "sha256-IjNQiQdZSwW8ZDNyUxJTuTBuhs9cpUjltOdwfzR4YKM=";
    };
    version = "3.2.10";
  }
  {
    id = "nhdogjmejiglipccpnnnanhbledajbpd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7F-rhLz8vsrofEjn8jv7DOf_PQmXaEc9iMT_kRPG7ovVDOkfHKeplDWBmLe8N4Jaid1cf9N8jGHcefc-mXIzLjnviF1-353-OPEcq-yHndHmYJMhpoGXWJxBWxeWbVAMZSmuU56gj3BzZrX5JliKSYUFEp46p_UQ/NHDOGJMEJIGLIPCCPNNNANHBLEDAJBPD_7_7_7_0.crx";
      name = "nhdogjmejiglipccpnnnanhbledajbpd.crx";
      hash = "sha256-v1ZcI/2eLAdO1HFE0FBDNveH5fEFOI9zxihG3ukvASQ=";
    };
    version = "7.7.7";
  }
  {
    id = "ienfalfjdbdpebioblfackkekamfmbnh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo6crQrcfQOGShTeR7q4xwvBGWgCpJtQr89ux7jCx3NbsNEgzyf-2odBFpE9R4mr_ywrw7vrQZZnRqG-s4G9Zou5_X0mI40JjUYH9kmigXRbU1LGQ8kUYZLwCX2y_QsAxlKa5aXWngrShOkRrp5-X9BCdXDDZGlF/IENFALFJDBDPEBIOBLFACKKEKAMFMBNH_1_8_0_0.crx";
      name = "ienfalfjdbdpebioblfackkekamfmbnh.crx";
      hash = "sha256-9BM0Q+2C5mHlWQyxVChKTMg6DDTlgOMibu9lG3Fd8QM=";
    };
    version = "1.8.0";
  }
  {
    id = "kmcfjchnmmaeeagadbhoofajiopoceel";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo5QKqW_utQkUxdG_9L9w9iS4HKcvrE_ZObu-GaamK6avJzW-nmoaKR-9v-FE0BiY54jHpn4ghTzinvN3mCAfpSiSCE-yfqadAQThtFgn2s0jGGkQrFmzg9JLGaSkuEAxlKa5VAofAd7esI9z1Wrl-4Nz4OnruVd/KMCFJCHNMMAEEAGADBHOOFAJIOPOCEEL_0_33_5_0.crx";
      name = "kmcfjchnmmaeeagadbhoofajiopoceel.crx";
      hash = "sha256-SaBM++yovHNqOUyurpcvsfotSUzHxgjc8GHvrLOOiGk=";
    };
    version = "0.33.5.0";
  }
  {
    id = "bhchdcejhohfmigjafbampogmaanbfkg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7jQmTVZcMnFOr6vBUh-O-sDdcMYIoxKpOsH0x35eXyuOjBhUORxTPuxeGfobeI0dWUQvPy6lArUyhZEQWS7lwYwRhTlJZcr0zDpN4ucalP_y59MPUEOmvggIO7GrsAxlKa5XBZ2gUX5R5WywYnKRN0Sn5gi2Um/BHCHDCEJHOHFMIGJAFBAMPOGMAANBFKG_0_6_6_0.crx";
      name = "bhchdcejhohfmigjafbampogmaanbfkg.crx";
      hash = "sha256-2n0HNRR2NRWTxO96ytORUedOiFAZmopmUHv/S43PB0k=";
    };
    version = "0.6.6";
  }
  {
    id = "hkgfoiooedgoejojocmhlaklaeopbecg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo78tvtu4DFbS-yJTGV5S7hVwO3IFjZ_y2DtrKD0TTy5J6OR0NNUo-IZk5T8Hvb6EfgX4Xp-BVimyCinM81QEBsb9tgeMxwaRbs4h1ZInRFHq_Q6KtP5aKcuFkFaewDGUprlPujG368BhCnayhoOLalQyO1zeMk/HKGFOIOOEDGOEJOJOCMHLAKLAEOPBECG_1_14_0_0.crx";
      name = "hkgfoiooedgoejojocmhlaklaeopbecg.crx";
      hash = "sha256-NaWNfAH9zyLIVpmK5+cb72PUZ3whU5NwCb+9BA45aGc=";
    };
    version = "1.14";
  }
  {
    id = "hipekcciheckooncpjeljhnekcoolahp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo4jno2Ga6CzgvWCf_oNWpHR74egMezTUGklTD0tKgSX_KlSHSuyjGuWX_CanUdD6YhD-qwYKpXBVXMFZ9R288Hyl7g_dThQJf2fVUwx6bDmvvIcAMZSmuXK7_yQbDCbsRe2zdkl_ohOKfns6g/HIPEKCCIHECKOONCPJELJHNEKCOOLAHP_2_6_0_0.crx";
      name = "hipekcciheckooncpjeljhnekcoolahp.crx";
      hash = "sha256-3a3HVG6dWVRx+EQ48gohNlu3BOzVZrpoZCxnf3chzRY=";
    };
    version = "2.6.0";
  }
  {
    id = "clngdbkpkpeebahjckkjfobafhncgmne";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7vuUcQjD3EvTtNNjWdo4xMHZUq1skNpSebqjXFeBOrCHH7RnC6zX_fIQ_x3tyVVkRxzoJ5rXdMIE9cfXjt6HMp6O-0SlaDXyQ_It1WujTKFJdOVDB8BGpeJwopuhUAxlKa5ciISvcVD4-5aWxprC8su431XHX0/CLNGDBKPKPEEBAHJCKKJFOBAFHNCGMNE_2_3_17_0.crx";
      name = "clngdbkpkpeebahjckkjfobafhncgmne.crx";
      hash = "sha256-b9MDjrRF/hLqWeniszhvZWRdg7bXM32DYVpMw6pOvks=";
    };
    version = "2.3.17";
  }
  {
    id = "gcknhkkoolaabfmlnjonogaaifnjlfnp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7uquIUh01fTu3wTVggQpn92DiA3JvSY6_wc30HFJmG31b4JGoOAxyh1THv0mCzK-uoA6ct--nn4VSP5EwjR96Ru0g9z9y_m02F0pCb-QMbXe06Q1AfusEGYpLgWTQAxlKa5avvJSUO3wg09-SYFi5MeJPDHg7A/GCKNHKKOOLAABFMLNJONOGAAIFNJLFNP_9_2_0_0.crx";
      name = "gcknhkkoolaabfmlnjonogaaifnjlfnp.crx";
      hash = "sha256-B0LnrmxNQ3B1iKk89jaIC6Q0k3IP3YEW6yJnW+n4sG4=";
    };
    version = "9.2";
  }
  {
    id = "nngceckbapebfimnlniiiahkandclblb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo4RD4l2aZ12swEdoUaUd6ZmHBNqPRqD_Th4KRKG6BsPWwTW8vI3lXVlRIxn8aDcMQB1mcYuwBVOvqxbMpFipgWT2mRoLQxgcEiCUJ6BZEI2PP-tPNq_PRHOXuD3HvXmAMZSmuWr4S1qNBC4TcojSq3DTNro5r_KGA/NNGCECKBAPEBFIMNLNIIIAHKANDCLBLB_2025_12_0_0.crx";
      name = "nngceckbapebfimnlniiiahkandclblb.crx";
      hash = "sha256-KOmTzxU1wDL49t0hBAsjfNUEiXTkKLoYI+Ls1RTWMK0=";
    };
    version = "2025.12.0";
  }
  {
    id = "kbmfpngjjgdllneeigpgjifpgocmfgmb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo5YwCgEO0Za2durB8EqzF11UuV21MAc5pRDp50dKWlFkPAdUf11JwbazuzTKhtYTn5Yf32pzRHkGXeQ3v3A25uEttPpOfDV2czR3ql8bXqprxcPrAXiPLR4UvfMuYyuAMZSmuWXTehP9KfhRyHMRSNrVZ86q7Whew/KBMFPNGJJGDLLNEEIGPGJIFPGOCMFGMB_5_24_8_0.crx";
      name = "kbmfpngjjgdllneeigpgjifpgocmfgmb.crx";
      hash = "sha256-wM2vceDp5M96hD7aPYEY0c9x1f/fK8Bz1UVokRTJyxg=";
    };
    version = "5.24.8";
  }
  {
    id = "dneaehbmnbhcippjikoajpoabadpodje";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7ClqBahlIp90Qoo3AsGhmVgXCUd0kc8KauIlal4xatqscl0x4bisz7pPVwM7O0QrUxkuxDi5YyI8BWwItYM6edL693PTrPZsGvJxEm3iBZqiC5OKIx3TNy3k6cHVIAxlKa5WdkT8gsWhYRps_KGJwxblN2DP40/DNEAEHBMNBHCIPPJIKOAJPOABADPODJE_2_0_9_0.crx";
      name = "dneaehbmnbhcippjikoajpoabadpodje.crx";
      hash = "sha256-26kMNZktrRomwltsAlQMEwiZ/MNv6Fw8GHoJ6GebsRE=";
    };
    version = "2.0.9";
  }
  {
    id = "cnojnbdhbhnkbcieeekonklommdnndci";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo4F5CfyOlkEkGDz1Cbv6yTOOx7i-fWAiDV6ZFcsTPMMgPeHSRMHQ9xbgdDcSyh7m6BTmADkO7V2VPOJFIgTpfui7-xzPzHywu25uT_Qg7lE9xIRIbI5nUgCoCr5bVAAxlKa5Xx-FyNsrJpdKJKjhOSNHyKylZkf/CNOJNBDHBHNKBCIEEEKONKLOMMDNNDCI_8_4_0_0.crx";
      name = "cnojnbdhbhnkbcieeekonklommdnndci.crx";
      hash = "sha256-DpIp5UeUbhXIwrbPqgXOqif9PbPc0wXVkXyx68XHcqY=";
    };
    version = "8.4.0";
  }
  {
    id = "pobhoodpcipjmedfenaigbeloiidbflp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AV8Xwo7kOqNEccDuxceUa5_4W1mHRjbiyhfBes-5qNcEE4UG8VnaNvPI053VkL5vXDW-RMwt8LHNCWmNLXcYtbj3yuryCFy_OCT66UVct3BBAmpph_GmsuHBb-ui2D3B-YUAxlKa5TeKLq2ri0ZgHToQLpRJcmVh1fGy/POBHOODPCIPJMEDFENAIGBELOIIDBFLP_6_4_1_0.crx";
      name = "pobhoodpcipjmedfenaigbeloiidbflp.crx";
      hash = "sha256-4sMXmTnApAGaK2aEhgp+Cp1vPweS78wRDn9cuYU0+VU=";
    };
    version = "6.4.1";
  }
]
