{ pkgs, ... }:
{
  home.packages = builtins.attrValues {
    inherit (pkgs.unstable)
      pavucontrol
      networkmanagerapplet
      desktop-file-utils
      unzip
      element-desktop
      hyprshot
      hyprcursor
      htop
      prismlauncher
      vscode-fhs
      gnumake
      nixfmt
      meson
      cmake
      font-manager
      python3
      uv
      nim
      nimble
      nimlsp
      nimlangserver
      nil
      nodejs
      grim
      swappy
      slurp
      nitch
      thunderbird-bin
      libreoffice
      p7zip
      file
      wlsunset
      killall
      piper
      playerctl
      feishin
      imagemagick
      gimp
      evince
      alsa-utils
      nmap
      keepassxc
      ;
    inherit (pkgs.unstable.kdePackages)
      kcalc
      ark
      okular
      ;
  };
}
