# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  config,
  lib,
  ...
}:
lib.lists.flatten [
  {
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H_d7iE5JTDYAxRBcOmcUoHYgWcMFsAtVm-84VlvOqZqZcKI97MXYu5JMiIPxyAxIb8U21mH3pWdyB7XlElE9-xa9J0IQMWDP7bRmGYRtOC5yvbhbylaCny_J5ktycGvAMZSmuWHSjehVpXvZf5yr4ef4YoBtDP1Ng/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_72_2_0.crx";
      name = "cjpalhdlnbpafiamejdnhcphjbkeiagm.crx";
      hash = "sha256-bgLY5tzlae7HIbUx+cfShAPlQmRCQX1ahVoX3SiLVvg=";
    };
    version = "1.72.2";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H96JsgZGLWdMqMIQfTnqgVDcVEzywPn0tKAMOVqUwogC-HvvpYQ_p2zri6z3EN_7NyBI_9SzelcWvchoItYQhpTj2UFIrVzhFEVP7hxlsX3g4ks_83dbZyW-At1FOQAxlKa5csonIwI3UNvL_LfWdQnq2XeuTCr/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_7_26_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-G0ht0WUH+I5e7UJHbw9NvTKvV77rNjP8ox9PKbvJMYI=";
    };
    version = "26.7.26";
  }
  {
    id = "jinjaccalgkegednnccohejagnlnfdag";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9xrZ6j6XzUbbw3UQ6ElkW-SEF5Au_bXEXYhOPTviFrZAi2a7PuJFwcu--ZYVARFGHSXSSorThYHwvktvQ54O70SvYcQhKln2GDPcaiyFLUPcAtjNNTkVOIS6JEixAAxlKa5SUqe33a7ZSJZWPst8X2UxTsW2R9/JINJACCALGKEGEDNNCCOHEJAGNLNFDAG_2_45_0_0.crx";
      name = "jinjaccalgkegednnccohejagnlnfdag.crx";
      hash = "sha256-JJuOKQtfkTge/YVDiJq3POxZFKSIzdiv4DpDHIdsMJA=";
    };
    version = "2.45.0";
  }
  {
    id = "kpaaapnegfaaoimjpagopchdbmenfngl";
    crxPath = pkgs.fetchurl {
      url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx";
      name = "kpaaapnegfaaoimjpagopchdbmenfngl.crx";
      hash = "sha256-X4m1To1n/1zQGrzQPXPyR8KIA4JleyyAh5AjuS2BvYw=";
    };
    version = "10.1.1.0";
  }
  {
    id = "lckanjgmijmafbedllaakclkaicjfmnk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8IwXnU_B6EZBGzYQRTM7pQHHLYlmFJkxHXZQ0o2cQFR41ogq7HO7NOGBzLgOnZaJz-I_2DBiBMJDXghgoV13Iz8gG348SZ8RfL4i7RKNaImAwaAMZSmuWtOcw0MmTZho75r6RIRLOxtVj36Q/LCKANJGMIJMAFBEDLLAAKCLKAICJFMNK_1_26_0_0.crx";
      name = "lckanjgmijmafbedllaakclkaicjfmnk.crx";
      hash = "sha256-rMFzGyrQCJ85p93PDHIy7TU329AZuOjBvuzoeO1Yoxo=";
    };
    version = "1.26.0";
  }
  {
    id = "lkbebcjgcmobigpeffafkodonchffocl";
    crxPath = pkgs.fetchurl {
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-latest.crx&inline=false&commit=b1851e14c1ada643a9711486f2a66fc28f73ad61";
      name = "lkbebcjgcmobigpeffafkodonchffocl.crx";
      hash = "sha256-5bUa8eE58INGr429HMhoaDZwJ57xLE+gsr7wic3aAtU=";
    };
    version = "4.4.0.5";
  }
  {
    id = "lmkeolibdeeglfglnncmfleojmakecjb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H_5tfsoOOG8nDXcawlU02ZPxKBda1Erttrm8jX8OdByUtgpdl-JVSG1qBVgTalfgOuiJLYccP2JZiGUlcaO2J0hg0nQWrtcB-wMo87Tqj8_VfoAV9WzpWNtbNjyISEAxlKa5V3AAYsdrfHMsti6tW8gc1n7XvhL/LMKEOLIBDEEGLFGLNNCMFLEOJMAKECJB_2_24_4_0.crx";
      name = "lmkeolibdeeglfglnncmfleojmakecjb.crx";
      hash = "sha256-sBkN+cH3G1WIvx6b7Y2WnJW+PG+xa9CtDx116KSMu8k=";
    };
    version = "2.24.4";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8TxxYB0TCdWphFbSe5tLvYQ6hmCDpYFHnQNnX3JIdsBDU0da99H3iznUPhXyMqR0YoGumAXPq4RwK7SI2W0FiRnKinpRUUTo8kcjv0z69wR6Lq2w-_ms9-CnVKQsEAxlKa5etO9eWUP6IQKB4ZKBzRyQOAwHKA/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_6_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-VYf+K2qZRhAcoN3nxu/nanVcXuW21uY9/EjH9zbNtP8=";
    };
    version = "6.1.6";
  }
  (lib.lists.optionals (config.catppuccin.enable) [
    {
      id = "lnjaiaapbakfhlbjenjkhffcdpoompki";
      crxPath = pkgs.fetchurl {
        url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9gUi0u1wGTvAu4ENsXv8yF9Ut9I71h_xJ-CkDeeerDWi-4oU3C_8PFftn71qDCxlA8ACpYRfF8N94PzMFVERDIVu6Gf34z1BarfZJMZB68zLwBgN9VaFwykoEpVrQAxlKa5ZOR-ny3wbrgza6Y7PRBTZMPZIpV/LNJAIAAPBAKFHLBJENJKHFFCDPOOMPKI_1_6_1_0.crx";
        name = "lnjaiaapbakfhlbjenjkhffcdpoompki.crx";
        hash = "sha256-ym0nff+4QNPWR6QXDBzpxvAV4dIc8VV5m14uSs19HzU=";
      };
      version = "1.6.1";
    }
  ])
]
