# This file is auto-generated by an update script
# DO NOT edit manually
{ pkgs, config, lib }:
lib.flatten [
  {
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yQISk048_-c74zdTQ3ZPhAjTl--Qe3ifszPytfY56QR-I6bPPqKJUWR5Btxipuz2ArbGNbJQbXpny0_RO4a95_7AFl3aCLa-1dugEukXUR8LB8coF5eZEsoM5TTEYU-AMZSmuVOTWHin6XHZu3bB4WNyjqEQ4BJDw/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_66_4_0.crx";
      name = "cjpalhdlnbpafiamejdnhcphjbkeiagm.crx";
      hash = "sha256-ts7jz6m7cq92MS/33P8XNDYn8wl9sML+SqhNEVXGkxQ=";
    };
    version = "1.66.4";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yTIVtWxe09_zKKdzeqQEjK-4yxrWfkpudktVvq5d5mleZYYwzgLKkHkQeScpNde0sHB8B8OON0GewOufMd4D_EqhIvWRejWDZxwDMAsaKXovzufCT-mqCUT-NCbMWkAxlKa5fqdqa5EgdVeILFwU1vkrvlvmgnF/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_25_10_2_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-mNhRCsZiAPBYTwdMJ8smtWhivBZ3VrKrtpO6t7evtDo=";
    };
    version = "25.10.2";
  }
  {
    id = "jinjaccalgkegednnccohejagnlnfdag";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yTHVHvX9K9E8FHT4RtiJj6H_dLBUaN_alqKfhmNhDwdL-FLtqSip3fxBd0mW6ZGsuhX5qoy1oH-4Rw4ikUV-zQ-omQnflcp69i8peYh9z5bq2qySMG3ZVUTJnCxTy0AxlKa5RLG7VPqM1hwuiLFtF2Z3oVzzwpS/JINJACCALGKEGEDNNCCOHEJAGNLNFDAG_2_31_0_0.crx";
      name = "jinjaccalgkegednnccohejagnlnfdag.crx";
      hash = "sha256-MF7a3ynX+A8QNrU0VLQQYG+QioZwC7lSVECjGidej28=";
    };
    version = "2.31.0";
  }
  {
    id = "lckanjgmijmafbedllaakclkaicjfmnk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yTYaiiOmj0y9qE_NRVnNbiKelmafz2vNIZYFPfYZb_HidtTF8aFWI5H1O6ygymHsBy_gLwbuOcsGjKIIlO9C1B85faMXzgRUFHOlw6H34rcTFwXAMZSmuUg_CnjVOuPKewNN5vC-JAzwaX36w/LCKANJGMIJMAFBEDLLAAKCLKAICJFMNK_1_26_0_0.crx";
      name = "lckanjgmijmafbedllaakclkaicjfmnk.crx";
      hash = "sha256-rMFzGyrQCJ85p93PDHIy7TU329AZuOjBvuzoeO1Yoxo=";
    };
    version = "1.26.0";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yRngFHI-UVPdiL9PeHfGxdbT1s_TJuUmP5yJ2WkqBxYNfmmTvU5foI_lHLynMM7JvNpJCRX7T06LvXB3VILXniNHyWjMJpYw5-v3ja-hisnRvHZ8FsIzXNiA4Sy9EwAxlKa5UMRdavLE59AUJijK4t-76e2fiCf/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_0_3_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-h6mEHOLZGxkgUbURsV1mMSxbirbHN/yH684F+TPc4Qw=";
    };
    version = "6.0.3";
  }
  {
    id = "lkbebcjgcmobigpeffafkodonchffocl";
    crxPath = pkgs.fetchurl {
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-latest.crx&inline=false&commit=e7f4a47541f982319842a29bc7e2a51a42cca439";
      name = "lkbebcjgcmobigpeffafkodonchffocl.crx";
      hash = "sha256-KWxo6EmShEUk2TWVCN/c3fjmrGltMtgAnBdSVb0V7p8=";
    };
    version = "4.2.3.0";
  }
  {
    id = "kpaaapnegfaaoimjpagopchdbmenfngl";
    crxPath = pkgs.fetchurl {
      url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx";
      name = "kpaaapnegfaaoimjpagopchdbmenfngl.crx";
      hash = "sha256-X4m1To1n/1zQGrzQPXPyR8KIA4JleyyAh5AjuS2BvYw=";
    };
    version = "10.1.1.0";
  }
  (lib.optionals (config.catppuccin.enable) [
    {
      id = "lnjaiaapbakfhlbjenjkhffcdpoompki";
      crxPath = pkgs.fetchurl {
        url = "https://clients2.googleusercontent.com/crx/blobs/AcLY-yTur7cQ0FLPWtvAtKdanpeu1tUgtp0Hp2Fm88rql035QxHmOrpMtesoA5FSsN2sOd4Y8OEtg0i5LYAcoiTKKHu-r2-i_pBv_qLAfQJwKaL164m2e5S7eyLYM6_CEwQAxlKa5UAtHRH8AKfJqeSA0t6_BwxKFoj3/LNJAIAAPBAKFHLBJENJKHFFCDPOOMPKI_1_5_0_0.crx";
        name = "lnjaiaapbakfhlbjenjkhffcdpoompki.crx";
        hash = "sha256-xlMG4kw88NWqWRK8916tvgnW1U99I1234Lk/l9YHVJI=";
      };
      version = "1.5.0";
    }
  ])
]
