name: Flake Checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check-nixos:
    name: Check ${{ matrix.user }} (${{ matrix.config }}) - (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - config: blind-faith
            user: lay-by
          - config: nanachi
            user: bigshaq9999
          - config: nyx
            user: donteatoreo
          - config: signed-int16
            user: 2husecondary
          - config: unsigned-int32
            user: ashuramaruzxc
          - config: unsigned-int64
            user: ashuramaruzxc
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          extra-conf: |
            extra-experimental-features = nix-command flakes pipe-operator

      - name: Check Configuration
        run: |
          set -euo pipefail
          nix build --extra-experimental-features "nix-command flakes pipe-operator" \
            .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  check-darwin:
    name: Check ${{ matrix.user }} (${{ matrix.config }}) - (Darwin)
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - config: anons-Mac-mini
            user: donteatoreo
          - config: faputa
            user: bigshaq9999
          - config: unsigned-int8
            user: ashuramaruzxc
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          source-url: https://install.lix.systems/lix/lix-installer-aarch64-darwin
          extra-conf: |
            extra-experimental-features = nix-command flakes pipe-operator

      - name: Check Configuration
        run: |
          set -euo pipefail
          # For nix run, you pass the flags to nix itself
          sudo nix --extra-experimental-features "nix-command flakes pipe-operator" \
            run nix-darwin -- check --flake .#${{ matrix.config }}
