name: Flake Checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  flake-check:
    name: General Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      
      - name: Run Flake Checker
        uses: DeterminateSystems/flake-checker-action@main
        with:
          check-outdated: true
          check-owner: true
          check-supported: true
          fail-mode: true
          ignore-missing-flake-lock: false

      - name: Run Nix Flake Check
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix flake check --show-trace

  # Linux NixOS Configurations
  check-blind-faith:
    name: Check blind-faith (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#blind-faith

  check-nanachi:
    name: Check nanachi (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#nanachi

  check-nyx:
    name: Check nyx (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#nyx

  check-signed-int16:
    name: Check signed-int16 (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#signed-int16

  check-unsigned-int32:
    name: Check unsigned-int32 (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#unsigned-int32

  check-unsigned-int64:
    name: Check unsigned-int64 (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nixos-rebuild check --flake .#unsigned-int64

  # Darwin Configurations
  check-anons-mac-mini:
    name: Check anons-Mac-mini (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          darwin-rebuild check --flake .#anons-Mac-mini

  check-faputa:
    name: Check faputa (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          darwin-rebuild check --flake .#faputa

  check-unsigned-int8:
    name: Check unsigned-int8 (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          darwin-rebuild check --flake .#unsigned-int8
