name: Flake Checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  flake-check:
    name: General Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux

      - name: Run Nix Flake Check
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix flake check --show-trace --no-pure-eval

  # Linux NixOS Configurations
  check-blind-faith:
    name: Check lay-by (blind-faith) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.blind-faith.config.system.build.toplevel

  check-nanachi:
    name: Check bigshaq9999 (nanachi) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.nanachi.config.system.build.toplevel

  check-nyx:
    name: Check donteatoreo (nyx) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.nyx.config.system.build.toplevel

  check-signed-int16:
    name: Check 2husecondary (signed-int16) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.signed-int16.config.system.build.toplevel

  check-unsigned-int32:
    name: Check ashuramaruzxc (unsigned-int32) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.unsigned-int32.config.system.build.toplevel

  check-unsigned-int64:
    name: Check ashuramaruzxc (unsigned-int64) - (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          nix build .#nixosConfigurations.unsigned-int64.config.system.build.toplevel

  # Darwin Configurations
  check-anons-mac-mini:
    name: Check donteatoreo (anons-Mac-mini) - (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          sudo nix run nix-darwin -- check --flake .#anons-Mac-mini

  check-faputa:
    name: Check bigshaq9999 (faputa) - (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          sudo nix run nix-darwin -- check --flake .#faputa

  check-unsigned-int8:
    name: Check ashuramaruzxc (unsigned-int8) - (Darwin)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Check Configuration
        run: |
          set -euo pipefail
          export NIX_CONFIG="extra-experimental-features = nix-command flakes pipe-operators"
          sudo nix run nix-darwin -- check --flake .#unsigned-int8
