name: Flake Checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check-nixos:
    name: Check ${{ matrix.user }} (${{ matrix.config }}) - (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - config: blind-faith
            user: lay-by
          - config: nanachi
            user: bigshaq9999
          - config: nyx
            user: flameflag
          - config: signed-int16
            user: 2husecondary
          - config: unsigned-int32
            user: ashuramaruzxc
          - config: unsigned-int64
            user: ashuramaruzxc
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux

      - name: Check Configuration
        run: |
          set -euo pipefail
          nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  check-darwin:
    name: Check ${{ matrix.user }} (${{ matrix.config }}) - (Darwin)
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - config: anons-Mac-mini
            user: flameflag
          - config: faputas.Mac-mini
            user: bigshaq9999
          - config: unsigned-int8
            user: ashuramaruzxc
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          source-url: https://install.lix.systems/lix/lix-installer-aarch64-darwin

      - name: Check Configuration
        run: |
          set -euo pipefail
          sudo nix run nix-darwin -- check --flake .#${{ matrix.config }}
